# -*- coding: utf-8 -*-
"""lab3_4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Q2zrVfjOc5AeRvlmtdQ-IMNNN84mx1zk

# Лабораторная работа 3, задача 4, вариант 17
"""

import matplotlib.pyplot as plt

def findInterval(xi, x0):
    for i in range(0,len(xi) - 1):
        if xi[i] <= x0 <= xi[i + 1]:
            return i

def firstDerivative(xi, yi, x0):
    i = findInterval(xi, x0)
    left = (yi[i + 1] - yi[i]) / (xi[i + 1] - xi[i])
    right = ((yi[i + 2] - yi[i + 1]) / (xi[i + 2] - xi[i + 1]) - left) / \
            (xi[i + 2] - xi[i]) * (2 * x0 - xi[i] - xi[i + 1])
    return left + right

def secondDerivative(xi, yi, x0):
    i = findInterval(xi, x0)
    left = (yi[i + 1] - yi[i]) / (xi[i + 1] - xi[i])
    right = 2 * ((yi[i + 2] - yi[i + 1]) / (xi[i + 2] - xi[i + 1]) - left) / \
            (xi[i + 2] - xi[i])
    return right

"""Вариант 17:

$$X^*=0.2$$
<table>
  <tr>
  <td>i</td><td>0</td><td>1</td><td>2</td><td>3</td><td>4</td>
  </tr>
  <tr>
  <td>$$x_i$$</td><td>-0.2</td><td>0.0</td><td>0.2</td><td>0.4</td><td>0.6</td>
  </tr>  
  <tr>
  <td>$$y_i$$</td><td>-0.40136</td><td>0.0</td><td>0.40136</td><td>0.81152</td><td>1.2435</td>
  </tr>    
</table>
"""

x0 = 0.2
xi = [-0.2, 0.0,	0.2,	0.4,	0.6]
yi = [-0.40136,	0.0,	0.40136,	0.81152,	1.2435]
print("Первая производная в точке = " + str(round(firstDerivative(xi, yi, x0), 6)))
print("Вторая производная в точке = " + str(round(secondDerivative(xi, yi, x0), 6)))

"""Построим графики, чтобы убедиться в правильности результатов:"""

plt.figure(figsize=(10,8))
plt.scatter(xi,yi,linewidths=5)
plt.plot(xi,yi,c="yellow",linewidth=3)
plt.legend(["Заданная выборка","Попарное соединение двух соседних точек"])

"""Зависимость почти линейная, поэтому тангенс угла наклона касательной в 0.2 равен примерно двум, что совпадает с результатом. И так как функция почти линейна, то вторая производная примерно равна нулю, что видно из второго результата работы программы"""